apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: chmocoder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: backend-image:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
        - name: REDIS_HOST
          value: redis
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: redis-config
              key: redis-port
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: redis-password
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: chmocoder
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: backend
