apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: chmocoder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: frontend-image:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5173
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: chmocoder
spec:
  ports:
  - port: 5173
    targetPort: 5173
  selector:
    app: frontend
  type: NodePort
