apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
  namespace: chmocoder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
      - name: proxy
        image: proxy-image:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        - containerPort: 443
        volumeMounts:
        - name: ssl-certs
          mountPath: /etc/ssl
      volumes:
      - name: ssl-certs
        hostPath:
          path: /home/docker/ssl
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: proxy
  namespace: chmocoder
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: https
    port: 443
    targetPort: 443
  selector:
    app: proxy
