apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: chmocoder
data:
  redis-port: "6379"

---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: chmocoder
type: Opaque
stringData:
  redis-password: cmVkaXM=
